sunny: Move to AIDL ServiceTracker
- This should fix the following error:
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.qti.hardware.servicetrackeraidl.IServicetracker/default (@1)

Change-Id: I45ed6826eddd7cb904c71bd401a0b5a7bdbf0e45
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>